version: "3.8"

services: 
    mysqlserver:
        container_name: mysqlserver
        image: mysql:8.0.0
        restart: always
        ports: 
            - "1433:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=Test1234!
            - MYSQL_DATABASE=TaskboardDB
        volumes: 
            - mysqldata:/var/lib/mysql
    web-app:
        depends_on:
            - mysqlserver
        container_name: web-app
        build:
            dockerfile: ./TaskBoard.WebApp/Dockerfile
        ports: 
            - "5000:8080"
        restart: on-failure

volumes:
    mysqldata: